name: testt
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Core dependencies
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  shared_preferences: ^2.3.3
  http: ^1.2.2
  intl: any
  get_it: ^8.0.2

  # UI and Media Utilities
  fluttertoast: ^8.2.8
  another_flushbar: ^1.12.30
  cached_network_image: ^3.4.1
  flutter_svg: ^2.0.16
  image_picker: ^1.1.2
  pinput: ^5.0.0
  dotted_border: ^2.1.0
  video_player: ^2.9.2
  flutter_colorpicker: ^1.1.0
  country_picker: ^2.0.21


  # Localization
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  intl_utils: ^2.6.2
  build_runner: ^2.4.13
  freezed: ^2.5.7
  json_serializable: ^6.9.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svg/
